import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Navbar from "./Components/Shared/Navbar/Navbar";
import AuthProvider from "@/Context/AuthProvider";
import Footer from "./Components/Shared/Footer/Footer";

export const metadata = {
  title: "Win Tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body>
        <Toaster position="top-center" />
          <AuthProvider>
            <Navbar></Navbar>
            {children}
            <Footer></Footer>
          </AuthProvider>
      </body>
    </html>
  );
}
